"use client";
import { useCallback, useEffect, useState } from "react";
import { BarChart3, Loader2, Save, Trash2, Sparkles, FileSpreadsheet, FileText, Play } from "lucide-react";
import GlassCard from "@/components/GlassCard";

/** REPORT BUILDER — no-code (source · fields · filters · grouping · date range · metric · chart) and natural-language ("monthly supply volume by client with weight discrepancy"). Save, share by role, export Excel/PDF. Extends live Tally reports with cross-module analysis; does not duplicate them. */
const input = "bmx-input rounded-xl border border-biome-line bg-biome-bg px-3 py-2 text-[11.5px] text-biome-text outline-none";
export default function AdvancedBuilder() {
  const [meta, setMeta] = useState<any>(null); const [spec, setSpec] = useState<any>({ name: "New report", source: "trips", filters: [], groupBy: "client", groupByMonthOf: null, metric: { kind: "count" }, chart: "bar", roles: [] });
  const [result, setResult] = useState<any>(null); const [nl, setNl] = useState(""); const [notes, setNotes] = useState<string[]>([]); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const r = await fetch("/api/reports-builder", { cache: "no-store" }); setMeta(await r.json()); }, []);
  useEffect(() => { load(); }, [load]);
  async function post(body: any) { setBusy(true); try { const r = await fetch("/api/reports-builder", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); return await r.json(); } finally { setBusy(false); } }
  async function run(s = spec) { const j = await post({ action: "run", spec: s }); setResult(j.result); }
  async function parse() { const j = await post({ action: "parse", text: nl }); if (j.spec) { setSpec({ ...j.spec, roles: [] }); setResult(j.result); setNotes(j.notes || []); } }
  async function exportExcel() { if (!result) return; const ExcelJS = (await import("exceljs")).default; const wb = new ExcelJS.Workbook(); const ws = wb.addWorksheet("Summary"); ws.addRow(["Group", result.metricLabel, "Rows"]); result.series.forEach((s: any) => ws.addRow([s.label, s.value, s.rows])); const ws2 = wb.addWorksheet("Rows"); ws2.addRow(result.fields); result.rows.forEach((r: any) => ws2.addRow(result.fields.map((f: string) => r[f]))); const buf = await wb.xlsx.writeBuffer(); const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([buf])); a.download = `${spec.name}.xlsx`; a.click(); }
  async function exportPdf() { if (!result) return; const { jsPDF } = await import("jspdf"); const autoTable = (await import("jspdf-autotable")).default; const doc = new jsPDF(); doc.setFontSize(14); doc.text(spec.name, 14, 18); doc.setFontSize(9); doc.text(`${result.metricLabel} · ${result.total} rows · generated ${new Date().toLocaleString("en-IN")}`, 14, 25); autoTable(doc, { startY: 30, head: [["Group", result.metricLabel, "Rows"]], body: result.series.map((s: any) => [s.label, s.value, s.rows]), headStyles: { fillColor: [22, 51, 0] } }); doc.save(`${spec.name}.pdf`); }
  const src = meta?.sources?.[spec.source]; const max = result ? Math.max(1, ...result.series.map((s: any) => s.value)) : 1;
  return (
    <div className="space-y-5">
      <header><h2 className="text-[15px] font-semibold text-biome-text">Custom cross-module builder (admin)</h2><p className="mt-2 text-[12px] text-biome-muted">Ask in plain words or build it field by field. Cross-module data from the app itself; Tally reports stay in Reports.</p></header>
      <GlassCard className="p-4"><p className="flex items-center gap-1.5 text-[9.5px] font-bold uppercase tracking-[.16em] text-biome-muted"><Sparkles size={12} /> Natural language</p><div className="mt-2 flex gap-2"><input value={nl} onChange={(e) => setNl(e.target.value)} placeholder='e.g. "monthly supply volume by client with weight discrepancy", "imprest spend by category this month", "POs remaining by party"' className={`${input} flex-1`} /><button onClick={parse} disabled={busy || !nl} className="bmx-btn rounded-xl bg-biome-leaf px-4 py-2 text-[11.5px] font-bold text-white disabled:opacity-50">Generate</button></div>{notes.map((n, i) => <p key={i} className="mt-1 text-[10.5px] text-biome-muted">{n}</p>)}</GlassCard>
      {meta && (
        <div className="grid gap-3 lg:grid-cols-[1fr,1.4fr]">
          <GlassCard className="p-4 space-y-2">
            <input value={spec.name} onChange={(e) => setSpec({ ...spec, name: e.target.value })} className={`${input} w-full`} />
            <select value={spec.source} onChange={(e) => setSpec({ ...spec, source: e.target.value, groupBy: null, groupByMonthOf: null, filters: [], metric: { kind: "count" } })} className={`${input} w-full`}>{Object.entries(meta.sources).map(([k, v]: any) => <option key={k} value={k}>{v.label}</option>)}</select>
            <div className="grid grid-cols-2 gap-1.5"><select value={spec.groupBy || ""} onChange={(e) => setSpec({ ...spec, groupBy: e.target.value || null })} className={input}><option value="">No grouping</option>{src.fields.map((f: string) => <option key={f} value={f}>by {f}</option>)}</select><select value={spec.groupByMonthOf || ""} onChange={(e) => setSpec({ ...spec, groupByMonthOf: e.target.value || null, chart: e.target.value ? "line" : spec.chart })} className={input}><option value="">Not per month</option>{src.dates.map((f: string) => <option key={f} value={f}>per month of {f}</option>)}</select></div>
            <div className="grid grid-cols-2 gap-1.5"><select value={spec.metric.kind} onChange={(e) => setSpec({ ...spec, metric: { ...spec.metric, kind: e.target.value } })} className={input}><option value="count">count</option><option value="sum">sum</option><option value="avg">average</option></select><select value={spec.metric.field || ""} onChange={(e) => setSpec({ ...spec, metric: { ...spec.metric, field: e.target.value || undefined } })} className={input} disabled={spec.metric.kind === "count"}><option value="">field…</option>{src.numeric.map((f: string) => <option key={f} value={f}>{f}</option>)}</select></div>
            <div className="grid grid-cols-2 gap-1.5"><input type="date" value={spec.from || ""} onChange={(e) => setSpec({ ...spec, from: e.target.value })} className={input} /><input type="date" value={spec.to || ""} onChange={(e) => setSpec({ ...spec, to: e.target.value })} className={input} /></div>
            <div className="space-y-1">{spec.filters.map((f: any, i: number) => <div key={i} className="grid grid-cols-[1fr,80px,1fr,auto] gap-1"><select value={f.field} onChange={(e) => setSpec({ ...spec, filters: spec.filters.map((x: any, j: number) => (j === i ? { ...x, field: e.target.value } : x)) })} className={input}>{src.fields.map((x: string) => <option key={x}>{x}</option>)}</select><select value={f.op} onChange={(e) => setSpec({ ...spec, filters: spec.filters.map((x: any, j: number) => (j === i ? { ...x, op: e.target.value } : x)) })} className={input}>{["is", "is_not", "contains", "gt", "lt"].map((o) => <option key={o}>{o}</option>)}</select><input value={f.value} onChange={(e) => setSpec({ ...spec, filters: spec.filters.map((x: any, j: number) => (j === i ? { ...x, value: e.target.value } : x)) })} className={input} /><button onClick={() => setSpec({ ...spec, filters: spec.filters.filter((_: any, j: number) => j !== i) })} className="text-rose-500"><Trash2 size={12} /></button></div>)}<button onClick={() => setSpec({ ...spec, filters: [...spec.filters, { field: src.fields[0], op: "is", value: "" }] })} className="text-[10.5px] font-semibold text-biome-leafBright">+ filter</button></div>
            <div className="flex flex-wrap gap-1.5"><select value={spec.chart} onChange={(e) => setSpec({ ...spec, chart: e.target.value })} className={input}><option value="bar">bar</option><option value="line">line</option><option value="table">table</option></select><select value={(spec.roles || [])[0] || ""} onChange={(e) => setSpec({ ...spec, roles: e.target.value ? [e.target.value] : [] })} className={input}><option value="">share: everyone with Reports</option>{["admin", "accounts", "coordinator", "plant_manager"].map((r) => <option key={r} value={r}>share: {r}</option>)}</select></div>
            <div className="flex flex-wrap gap-1.5"><button onClick={() => run()} disabled={busy} className="bmx-btn flex items-center gap-1 rounded-xl bg-biome-leaf px-4 py-2 text-[11.5px] font-bold text-white"><Play size={12} /> Run</button><button onClick={async () => { await post({ action: "save", spec }); await load(); }} className="bmx-chip flex items-center gap-1 rounded-xl border border-biome-line px-3 py-2 text-[11px] font-semibold text-biome-muted"><Save size={12} /> Save</button><button onClick={exportExcel} disabled={!result} className="bmx-chip flex items-center gap-1 rounded-xl border border-biome-line px-3 py-2 text-[11px] font-semibold text-biome-muted disabled:opacity-50"><FileSpreadsheet size={12} /> Excel</button><button onClick={exportPdf} disabled={!result} className="bmx-chip flex items-center gap-1 rounded-xl border border-biome-line px-3 py-2 text-[11px] font-semibold text-biome-muted disabled:opacity-50"><FileText size={12} /> PDF</button></div>
            {meta.saved.filter((s: any) => !s.module).length > 0 && <div className="mt-2 border-t border-biome-line pt-2"><p className="text-[9.5px] font-bold uppercase tracking-[.14em] text-biome-muted">Saved</p>{meta.saved.filter((s: any) => !s.module).map((s: any) => <div key={s.id} className="flex items-center gap-2 text-[11px] text-biome-text"><button onClick={() => { setSpec(s); run(s); }} className="flex-1 text-left hover:text-biome-leafBright">{s.name}</button><button onClick={async () => { await post({ action: "delete", id: s.id }); await load(); }} className="text-rose-500"><Trash2 size={11} /></button></div>)}</div>}
          </GlassCard>
          <GlassCard className="p-4">
            {!result ? <p className="flex items-center gap-1.5 text-[11.5px] text-biome-muted"><BarChart3 size={14} /> Run a report to see it here.</p> : (<>
              <p className="text-[9.5px] font-bold uppercase tracking-[.16em] text-biome-muted">{spec.name} · {result.metricLabel} · {result.total} rows</p>
              {spec.chart !== "table" && <svg viewBox="0 0 600 240" className="mt-2 w-full">{result.series.slice(0, 24).map((s: any, i: number, arr: any[]) => { const w = 560 / arr.length; const h = (s.value / max) * 180; return spec.chart === "bar" ? <g key={s.label}><rect x={30 + i * w + 2} y={200 - h} width={Math.max(2, w - 4)} height={h} rx={3} fill="#9fe870" /><text x={30 + i * w + w / 2} y={214} textAnchor="middle" fontSize={7} fill="rgb(var(--c-muted))">{String(s.label).slice(0, 10)}</text><text x={30 + i * w + w / 2} y={196 - h} textAnchor="middle" fontSize={7} fill="rgb(var(--c-text))">{s.value}</text></g> : <g key={s.label}>{i > 0 && <line x1={30 + (i - 0.5) * w} y1={200 - (arr[i - 1].value / max) * 180} x2={30 + (i + 0.5) * w} y2={200 - h} stroke="#9fe870" strokeWidth={2} />}<circle cx={30 + (i + 0.5) * w} cy={200 - h} r={3} fill="#163300" stroke="#9fe870" /><text x={30 + (i + 0.5) * w} y={214} textAnchor="middle" fontSize={7} fill="rgb(var(--c-muted))">{String(s.label).slice(0, 10)}</text></g>; })}</svg>}
              <table className="mt-2 w-full text-left text-[11px]"><thead><tr className="text-[9px] uppercase tracking-[.1em] text-biome-muted"><th className="py-1">Group</th><th>{result.metricLabel}</th><th>Rows</th></tr></thead><tbody>{result.series.map((s: any) => <tr key={s.label} className="border-t border-biome-line/60 text-biome-text"><td className="py-1">{s.label}</td><td className="font-mono">{s.value}</td><td className="font-mono text-biome-muted">{s.rows}</td></tr>)}</tbody></table>
            </>)}
          </GlassCard>
        </div>)}
    </div>);
}
