"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { FolderSearch, Search, Loader2, Copy, CalendarX, FileWarning } from "lucide-react";
import GlassCard from "@/components/GlassCard";

/** DOCUMENT INTELLIGENCE VAULT — one search across every document the app holds (KYC, company, contracts, evidence, forms, POs), entity-linked, with duplicates, expiries and missing-document relationships. Search tolerates different filenames and spellings (token + trigram matching — no embedding model, said plainly). */
export default function VaultPage() {
  const [q, setQ] = useState(""); const [res, setRes] = useState<any[] | null>(null); const [intel, setIntel] = useState<any>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { fetch("/api/vault").then((r) => r.json()).then(setIntel); }, []);
  useEffect(() => { if (!q.trim()) { setRes(null); return; } const t = setTimeout(async () => { setBusy(true); const r = await fetch(`/api/vault?q=${encodeURIComponent(q)}`); const j = await r.json(); setRes(j.results || []); setBusy(false); }, 300); return () => clearTimeout(t); }, [q]);
  return (
    <div className="space-y-5">
      <header><p className="text-[10px] font-bold uppercase tracking-[.2em] text-biome-muted">Biome AI OS</p><h1 className="biome-shout mt-1 text-[30px] leading-[1.05] text-biome-text">Vault<span className="text-biome-leafBright">.</span></h1><p className="mt-2 text-[12px] text-biome-muted">"All contracts related to Vendor ABC", "GST certificate Terra", "cancelled cheque" — finds it even when the filename says something else.</p></header>
      <div className="relative"><Search size={15} className="absolute left-4 top-1/2 -translate-y-1/2 text-biome-muted" /><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search every document…" className="bmx-input w-full rounded-2xl border border-biome-line bg-biome-bg py-3.5 pl-11 pr-4 text-[13px] text-biome-text outline-none" />{busy && <Loader2 size={14} className="bmx-spin absolute right-4 top-1/2 -translate-y-1/2 text-biome-muted" />}</div>
      {res && <div className="space-y-1.5">{res.length === 0 && <GlassCard className="p-6"><p className="text-[11.5px] text-biome-muted">Nothing matched.</p></GlassCard>}{res.map(({ doc, score }: any) => <Link key={doc.id} href={doc.href} className="bmx-card flex items-center gap-3 rounded-2xl border border-biome-line bg-biome-bgSoft px-4 py-2.5"><span className="rounded-full border border-biome-line px-2 py-0.5 text-[9px] font-bold uppercase text-biome-muted">{doc.source}</span><span className="min-w-0 flex-1"><span className="block truncate text-[12px] font-semibold text-biome-text">{doc.title}</span><span className="block truncate text-[10.5px] text-biome-muted">{doc.fileName} · {doc.type}{doc.entity ? ` · ${doc.entity.name}` : ""} · {doc.date}{doc.expiresOn ? ` · expires ${doc.expiresOn}` : ""}</span></span><span className="text-[9.5px] text-biome-muted">match {Math.round(score * 10)}</span></Link>)}</div>}
      {!res && intel && (
        <div className="grid gap-3 lg:grid-cols-3">
          <GlassCard className="p-4"><p className="flex items-center gap-1.5 text-[9.5px] font-bold uppercase tracking-[.16em] text-biome-muted"><FolderSearch size={12} /> Index · {intel.intelligence.total} documents</p><ul className="mt-2 space-y-0.5 text-[11px] text-biome-text">{Object.entries(intel.intelligence.bySource).map(([k, v]: any) => <li key={k} className="flex justify-between"><span>{k}</span><span className="font-mono text-biome-muted">{v}</span></li>)}</ul></GlassCard>
          <GlassCard className="p-4"><p className="flex items-center gap-1.5 text-[9.5px] font-bold uppercase tracking-[.16em] text-biome-muted"><CalendarX size={12} /> Expiring · 45 days</p>{intel.intelligence.expiring.length === 0 && <p className="mt-2 text-[11px] text-biome-muted">Nothing expiring.</p>}<ul className="mt-2 space-y-0.5">{intel.intelligence.expiring.slice(0, 10).map((x: any) => <li key={x.doc.id} className="text-[11px] text-biome-text"><Link href={x.doc.href}>{x.doc.title}{x.doc.entity ? ` — ${x.doc.entity.name}` : ""}</Link> <span className={x.days < 0 ? "text-rose-500" : "text-amber-600"}>{x.days < 0 ? `expired ${-x.days}d ago` : `${x.days}d`}</span></li>)}</ul></GlassCard>
          <GlassCard className="p-4"><p className="flex items-center gap-1.5 text-[9.5px] font-bold uppercase tracking-[.16em] text-biome-muted"><Copy size={12} /> Duplicates · <FileWarning size={12} /> missing</p>{intel.intelligence.duplicates.length === 0 && intel.intelligence.missing.length === 0 && <p className="mt-2 text-[11px] text-biome-muted">No duplicates, nothing missing.</p>}<ul className="mt-2 space-y-0.5">{intel.intelligence.duplicates.slice(0, 6).map((d: any, i: number) => <li key={i} className="text-[11px] text-biome-text">{d.a.title} ↔ {d.b.title} <span className="text-biome-muted">— {d.why}</span></li>)}{intel.intelligence.missing.slice(0, 6).map((m: any) => <li key={m.party} className="text-[11px] text-rose-500">{m.party}: missing {m.missing.join(", ")}</li>)}</ul></GlassCard>
        </div>)}
      {!res && intel && <div className="space-y-1"><p className="text-[9.5px] font-bold uppercase tracking-[.16em] text-biome-muted">Recent</p>{intel.recent.slice(0, 15).map((d: any) => <Link key={d.id} href={d.href} className="block rounded-xl border border-biome-line bg-biome-bgSoft px-3 py-2 text-[11px] text-biome-text">{d.title} <span className="text-biome-muted">· {d.source} · {d.entity?.name || ""} · {d.date}</span></Link>)}</div>}
    </div>);
}
