/**
 * Rule-based automation "agent" for the Biome Industria platform.
 *
 * This is intentionally NOT a call to any external AI API. Everything here
 * runs synchronously in the browser using plain keyword matching and date
 * math, so it works fully offline and has zero ongoing cost.
 */

export interface AgentRoute {
  href: string;
  label: string;
}

export interface AgentReply {
  text: string;
  route?: AgentRoute;
}

interface Rule {
  id: string;
  keywords: string[];
  reply: (query: string) => AgentReply;
}

const RULES: Rule[] = [
  {
    id: "reconcile-ledger",
    keywords: ["reconcile", "ledger", "match books", "compare ledger"],
    reply: () => ({
      text: "I can take you to Ledger Reconciliation — upload Ledger A and Ledger B there and I'll auto-detect the columns for you.",
      route: { href: "/reconciliation", label: "Open Ledger Reconciliation" },
    }),
  },
  {
    id: "gst",
    keywords: ["gst", "gstr", "gstr1", "gstr-1", "gstr2b", "gstr-2b", "gstr3b", "gstr-3b", "tax return", "itc"],
    reply: () => ({
      text: "Head to GST Compliance to reconcile GSTR-1, GSTR-2B or GSTR-3B against your books, with a full mismatch report.",
      route: { href: "/gst-compliance", label: "Open GST Compliance" },
    }),
  },
  {
    id: "ocr",
    keywords: ["ocr", "scan", "invoice image", "extract", "photo", "receipt"],
    reply: () => ({
      text: "The OCR Scanner reads invoices/receipts (image or PDF) and gives you a clean Excel or PDF export.",
      route: { href: "/ocr", label: "Open OCR Scanner" },
    }),
  },
  {
    id: "whatsapp",
    keywords: ["whatsapp", "documents received", "auto save"],
    reply: () => ({
      text: "Documents that come in over WhatsApp Business are auto-sorted by month and client — check the WhatsApp Documents tab.",
      route: { href: "/whatsapp", label: "Open WhatsApp Documents" },
    }),
  },
  {
    id: "export",
    keywords: ["export", "download", "excel", "pdf report", "csv"],
    reply: () => ({
      text: "Every module (Reconciliation, GST Compliance, OCR) has export buttons at the bottom of its results — Excel and CSV/PDF, both fully offline, no data leaves your browser.",
    }),
  },
  {
    id: "due-dates",
    keywords: ["due date", "deadline", "when to file", "last date"],
    reply: () => ({ text: dueDateSummary() }),
  },
  {
    id: "help",
    keywords: ["help", "what can you do", "hi", "hello", "hey"],
    reply: () => ({
      text: "I'm a rule-based assistant — I run fully in your browser, no internet or paid API needed. I can point you to Reconciliation, GST Compliance, OCR, or WhatsApp Documents, and remind you of GST due dates. Try asking \"gst due dates\" or \"reconcile ledger\".",
    }),
  },
];

export function dueDateSummary(now: Date = new Date()): string {
  const day = now.getDate();
  const monthName = now.toLocaleDateString("en-IN", { month: "long" });
  const lines = [
    `GSTR-1: 11th of every month${day <= 11 ? " (upcoming this month)" : " (passed for " + monthName + ")"}`,
    `GSTR-3B: 20th of every month${day <= 20 ? " (upcoming this month)" : " (passed for " + monthName + ")"}`,
    "GSTR-2B: auto-generated by the portal, usually by the 14th — no separate filing",
  ];
  return `Standard monthly due dates:\n${lines.join("\n")}\n(Always confirm against the latest CBIC notification for your filing frequency.)`;
}

/** Same keyword matching as matchIntent, but returns null instead of a
 *  canned "I didn't recognise that" reply when nothing matches — lets a
 *  caller fall through to the local AI model for open-ended questions
 *  while still using instant, zero-cost rule matching for common app
 *  navigation commands. */
export function tryMatchIntent(query: string): AgentReply | null {
  const q = query.toLowerCase().trim();
  if (!q) return null;
  for (const rule of RULES) {
    if (rule.keywords.some((kw) => q.includes(kw))) {
      return rule.reply(q);
    }
  }
  return null;
}

export function matchIntent(query: string): AgentReply {
  const q = query.toLowerCase().trim();
  if (!q) {
    return { text: "Ask me about reconciliation, GST filing, OCR scanning, or WhatsApp documents." };
  }
  for (const rule of RULES) {
    if (rule.keywords.some((kw) => q.includes(kw))) {
      return rule.reply(q);
    }
  }
  return {
    text: "I didn't recognise that — I only understand a fixed set of app commands (I'm rule-based, not a language model). Try \"help\" to see what I can do.",
  };
}
