/**
 * Biome Platform — one look for every Excel the app hands out
 * -------------------------------------------------------------------
 * The biomass sheet, the transport sheet, the coordination register and
 * the report builder all build their workbooks through this file, so a
 * download from any of them reads as the same company's document:
 *
 *   ┌ logo │ BIOME INDUSTRIA PRIVATE LIMITED                         ┐
 *   │      │ Report title                                            │
 *   │      │ Plant · Period · Generated by … on …                    │
 *   ├──────┴─────────────── thin brand bar ─────────────────────────┤
 *   │ coloured header row (frozen, auto-filter, wrapped)            │
 *   │ zebra data rows, ₹ / kg / date formats, status colours        │
 *   │ TOTAL row                                                     │
 *   └───────────────────────────────────────────────────────────────┘
 *
 * Plus print setup (A4 landscape, fit to one page wide, header row
 * repeated on every page, page x of y in the footer).
 *
 * Pure — no fs, no Node APIs — so the browser (report builder) and the
 * server routes share it. The logo bytes are passed in by the caller
 * (lib/excelLogo.ts on the server, a fetch of /icons/icon-192.png in the
 * browser). Takes the exceljs Workbook the caller created, so it never
 * imports exceljs itself.
 */

export const XL_COLORS = {
  brand: "FF14532D", // deep green — header row, company line
  leaf: "FF1F7A4C", // accent bar, sub-headings
  leafSoft: "FFE7F2EA", // totals row, summary headings
  zebra: "FFF5F9F6",
  line: "FFD3E2D7",
  ink: "FF1F2937",
  muted: "FF6B7280",
  white: "FFFFFFFF",
  red: "FFB42318",
  redSoft: "FFFDECEA",
  amber: "FF9A6700",
  amberSoft: "FFFFF4D6",
  green: "FF067647",
  greenSoft: "FFE3F6EA",
  blue: "FF175CD3",
  blueSoft: "FFE8F0FE",
  indigo: "FF3E3A9E",
  indigoSoft: "FFECEBFB",
  grey: "FF475467",
  greySoft: "FFF2F4F7",
};

export type XlType = "text" | "number" | "int" | "kg" | "money" | "pct" | "pct100" | "date";

export interface XlColumn {
  key: string;
  header: string;
  type?: XlType;
  /** Character width; worked out from the header and the data when absent. */
  width?: number;
  /** Summed in the TOTAL row. */
  total?: boolean;
  /** A live Excel formula for this cell, given its row number. */
  formula?: (row: number, letterOf: (key: string) => string) => string;
  /** Shown as a note on the header cell. */
  note?: string;
}

export interface XlMeta {
  company?: string;
  title: string;
  plant?: string;
  period?: string;
  generatedBy?: string;
  generatedAt?: Date;
  /** One more short line under the meta line (filters, counts). */
  note?: string;
}

export interface XlTone {
  fill: string;
  font: string;
}

export const TONES: Record<"red" | "amber" | "green" | "blue" | "indigo" | "grey", XlTone> = {
  red: { fill: XL_COLORS.redSoft, font: XL_COLORS.red },
  amber: { fill: XL_COLORS.amberSoft, font: XL_COLORS.amber },
  green: { fill: XL_COLORS.greenSoft, font: XL_COLORS.green },
  blue: { fill: XL_COLORS.blueSoft, font: XL_COLORS.blue },
  indigo: { fill: XL_COLORS.indigoSoft, font: XL_COLORS.indigo },
  grey: { fill: XL_COLORS.greySoft, font: XL_COLORS.grey },
};

/** Indian digit grouping (12,34,567.00), as the accounts team reads money. */
const INR_GROUPS = (prefix: string, dec: string) =>
  `[>=10000000]${prefix}##\\,##\\,##\\,##0${dec};[>=100000]${prefix}##\\,##\\,##0${dec};${prefix}##,##0${dec}`;

export function numFmtFor(type: XlType | undefined): string | undefined {
  switch (type) {
    case "money": return INR_GROUPS('"₹"', ".00");
    case "number": return "#,##0.00";
    case "kg": return "#,##0";
    case "int": return "0";
    case "pct": return "0.00%";
    case "pct100": return '0.00"%"';
    case "date": return "dd-mmm-yyyy";
    default: return undefined;
  }
}

export function colLetter(n: number): string {
  let s = "";
  while (n > 0) {
    const m = (n - 1) % 26;
    s = String.fromCharCode(65 + m) + s;
    n = Math.floor((n - 1) / 26);
  }
  return s;
}

/** "2026-09-12" (or a Date) → a real Excel date, so filters and sorting work. */
export function excelDate(v: unknown): Date | null {
  if (v instanceof Date) return isNaN(v.getTime()) ? null : v;
  const s = String(v ?? "").trim();
  const m = s.match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (!m) return null;
  return new Date(Date.UTC(Number(m[1]), Number(m[2]) - 1, Number(m[3])));
}

export function fmtStamp(d: Date = new Date()): string {
  return d.toLocaleString("en-IN", {
    day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit", timeZone: "Asia/Kolkata",
  });
}

/** "12-Sep-2026 to 30-Sep-2026" from the rows' ISO dates. */
export function periodOf(isoDates: string[]): string {
  const ds = isoDates.map((d) => String(d || "").slice(0, 10)).filter((d) => /^\d{4}-\d{2}-\d{2}$/.test(d)).sort();
  if (!ds.length) return "No dated rows";
  const f = (d: string) => {
    const dt = excelDate(d)!;
    return dt.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" });
  };
  return ds[0] === ds[ds.length - 1] ? f(ds[0]) : `${f(ds[0])} to ${f(ds[ds.length - 1])}`;
}

const thin = (argb: string = XL_COLORS.line) => ({ style: "thin", color: { argb } });
const solid = (argb: string) => ({ type: "pattern", pattern: "solid", fgColor: { argb } });

/** Register the logo once per workbook; pass the id to each sheet. */
export function addLogo(wb: any, png: Uint8Array | ArrayBuffer | null | undefined): number | null {
  if (!png) return null;
  try {
    const buffer = png instanceof ArrayBuffer ? new Uint8Array(png) : png;
    return wb.addImage({ buffer, extension: "png" });
  } catch {
    return null;
  }
}

/**
 * The letterhead: logo, company, title, meta line and a brand bar.
 * Returns the row number the table's header row should go on.
 */
export function letterhead(ws: any, meta: XlMeta, width: number, logoId: number | null): number {
  const span = Math.max(2, width);
  const from = logoId !== null ? 2 : 1;
  const lines: { text: string; size: number; bold: boolean; color: string; height: number }[] = [
    { text: meta.company || "BIOME INDUSTRIA PRIVATE LIMITED", size: 17, bold: true, color: XL_COLORS.brand, height: 27 },
    { text: meta.title, size: 12.5, bold: true, color: XL_COLORS.ink, height: 20 },
    {
      text: [
        meta.plant && `Plant: ${meta.plant}`,
        meta.period && `Period: ${meta.period}`,
        `Generated ${fmtStamp(meta.generatedAt || new Date())}${meta.generatedBy ? ` by ${meta.generatedBy}` : ""}`,
      ].filter(Boolean).join("   ·   "),
      size: 9.5, bold: false, color: XL_COLORS.muted, height: 16,
    },
  ];
  if (meta.note) lines.push({ text: meta.note, size: 9, bold: false, color: XL_COLORS.muted, height: 15 });

  lines.forEach((l, i) => {
    const r = i + 1;
    if (span > from) ws.mergeCells(r, from, r, span);
    const cell = ws.getCell(r, from);
    cell.value = l.text;
    cell.font = { name: "Calibri", size: l.size, bold: l.bold, color: { argb: l.color } };
    cell.alignment = { vertical: "middle", horizontal: "left", indent: 1 };
    ws.getRow(r).height = l.height;
  });
  const bar = lines.length + 1;
  for (let c = 1; c <= span; c++) ws.getCell(bar, c).fill = solid(XL_COLORS.leaf);
  ws.getRow(bar).height = 4;
  const spacer = bar + 1;
  ws.getRow(spacer).height = 6;

  if (logoId !== null) {
    try {
      ws.addImage(logoId, { tl: { col: 0.12, row: 0.15 }, ext: { width: 54, height: 54 }, editAs: "oneCell" });
    } catch { /* the heading reads fine without it */ }
  }
  return spacer + 1;
}

export function styleHeaderRow(ws: any, rowNo: number, cols: XlColumn[], startCol = 1) {
  const row = ws.getRow(rowNo);
  cols.forEach((c, i) => {
    const cell = row.getCell(startCol + i);
    cell.value = c.header;
    cell.font = { name: "Calibri", size: 10, bold: true, color: { argb: XL_COLORS.white } };
    cell.fill = solid(XL_COLORS.brand);
    cell.alignment = { vertical: "middle", horizontal: "center", wrapText: true };
    cell.border = { top: thin(XL_COLORS.brand), bottom: thin(XL_COLORS.brand), left: thin("FF2F6B47"), right: thin("FF2F6B47") };
    if (c.note) cell.note = c.note;
  });
  row.height = 32;
}

export interface TableOptions {
  meta: XlMeta;
  columns: XlColumn[];
  rows: Record<string, any>[];
  logoId?: number | null;
  /** Freeze this many columns on the left as well as the header. */
  freezeCols?: number;
  totals?: boolean;
  /** Label in the first column of the TOTAL row. */
  totalLabel?: string;
  /** Tint a whole row (frozen consignment, cancelled trip…). */
  rowTone?: (row: Record<string, any>, index: number) => XlTone | null;
  /** Colour one cell (status chip, mismatch…). */
  cellTone?: (key: string, value: any, row: Record<string, any>) => XlTone | null;
  /** Excel tab colour. */
  tabColor?: string;
  footerLeft?: string;
}

/**
 * A full report sheet: letterhead, header, data, totals, filter, freeze
 * and print setup. Returns the header and last data row numbers.
 */
export function buildTableSheet(wb: any, name: string, opt: TableOptions): { ws: any; headerRow: number; firstRow: number; lastRow: number } {
  const cols = opt.columns;
  const ws = wb.addWorksheet(safeSheetName(name), {
    properties: { tabColor: { argb: opt.tabColor || XL_COLORS.leaf }, defaultRowHeight: 18 },
  });
  const headerRow = letterhead(ws, opt.meta, cols.length, opt.logoId ?? null);
  styleHeaderRow(ws, headerRow, cols);

  const letters = new Map(cols.map((c, i) => [c.key, colLetter(i + 1)]));
  const letterOf = (k: string) => letters.get(k) || "A";
  const firstRow = headerRow + 1;

  opt.rows.forEach((r, i) => {
    const rowNo = firstRow + i;
    const row = ws.getRow(rowNo);
    const tone = opt.rowTone?.(r, i) || null;
    cols.forEach((c, ci) => {
      const cell = row.getCell(ci + 1);
      const raw = r[c.key];
      let value: any;
      if (c.type === "date") value = excelDate(raw) ?? (raw ? String(raw) : null);
      else if (c.type && c.type !== "text") {
        const n = typeof raw === "number" ? raw : raw === "" || raw === null || raw === undefined ? null : Number(String(raw).replace(/,/g, ""));
        value = n === null || !Number.isFinite(n) ? null : n;
      } else value = raw === null || raw === undefined ? "" : String(raw);
      if (c.formula) value = { formula: c.formula(rowNo, letterOf).replace(/^=/, ""), result: value ?? 0 };
      cell.value = value;
      const fmt = numFmtFor(c.type);
      if (fmt) cell.numFmt = fmt;
      cell.font = { name: "Calibri", size: 10, color: { argb: XL_COLORS.ink } };
      cell.alignment = {
        vertical: "middle",
        horizontal: c.type && c.type !== "text" ? (c.type === "date" ? "center" : "right") : "left",
      };
      cell.border = { bottom: thin(), left: thin("FFE6EEE8"), right: thin("FFE6EEE8") };
      const ct = opt.cellTone?.(c.key, raw, r);
      if (ct) {
        cell.fill = solid(ct.fill);
        cell.font = { name: "Calibri", size: 10, bold: true, color: { argb: ct.font } };
        if (!c.type || c.type === "text") cell.alignment = { vertical: "middle", horizontal: "center" };
      } else if (tone) {
        cell.fill = solid(tone.fill);
      } else if (i % 2 === 1) {
        cell.fill = solid(XL_COLORS.zebra);
      }
    });
  });

  const lastRow = firstRow + opt.rows.length - 1;
  if (opt.totals !== false && opt.rows.length) {
    const t = ws.getRow(lastRow + 1);
    cols.forEach((c, ci) => {
      const cell = t.getCell(ci + 1);
      if (ci === 0) cell.value = opt.totalLabel || `TOTAL (${opt.rows.length})`;
      else if (c.total) {
        const L = colLetter(ci + 1);
        const sum = opt.rows.reduce((s, r) => {
          const n = Number(String(r[c.key] ?? "").replace(/,/g, ""));
          return s + (Number.isFinite(n) ? n : 0);
        }, 0);
        cell.value = { formula: `SUBTOTAL(9,${L}${firstRow}:${L}${lastRow})`, result: round2(sum) };
        const fmt = numFmtFor(c.type);
        if (fmt) cell.numFmt = fmt;
        cell.alignment = { horizontal: "right", vertical: "middle" };
      }
      cell.font = { name: "Calibri", size: 10.5, bold: true, color: { argb: XL_COLORS.brand } };
      cell.fill = solid(XL_COLORS.leafSoft);
      cell.border = { top: { style: "medium", color: { argb: XL_COLORS.leaf } }, bottom: { style: "double", color: { argb: XL_COLORS.leaf } } };
    });
    t.height = 22;
  }

  if (!opt.rows.length) {
    ws.mergeCells(firstRow, 1, firstRow, Math.max(1, cols.length));
    const c = ws.getCell(firstRow, 1);
    c.value = "No rows for this selection.";
    c.font = { italic: true, color: { argb: XL_COLORS.muted } };
    c.alignment = { horizontal: "center" };
  }

  // Widths from the header and the data (bounded), unless the caller set one.
  cols.forEach((c, ci) => {
    if (c.width) { ws.getColumn(ci + 1).width = c.width; return; }
    let w = Math.min(28, Math.max(8, Math.ceil(c.header.length * 0.75) + 3));
    for (const r of opt.rows.slice(0, 400)) {
      const v = r[c.key];
      const len = c.type === "date" ? 12 : c.type === "money" ? String(Math.round(Number(v) || 0)).length + 6 : String(v ?? "").length + 2;
      if (len > w) w = Math.min(c.type && c.type !== "text" ? 18 : 42, len);
    }
    ws.getColumn(ci + 1).width = w;
  });
  if ((opt.logoId ?? null) !== null && (ws.getColumn(1).width || 0) < 9) ws.getColumn(1).width = 9;

  ws.views = [{ state: "frozen", xSplit: opt.freezeCols || 0, ySplit: headerRow, topLeftCell: `${colLetter((opt.freezeCols || 0) + 1)}${headerRow + 1}`, showGridLines: false }];
  if (opt.rows.length) {
    ws.autoFilter = { from: { row: headerRow, column: 1 }, to: { row: lastRow, column: cols.length } };
  }
  printSetup(ws, headerRow, opt.footerLeft || opt.meta.title);
  return { ws, headerRow, firstRow, lastRow };
}

export function printSetup(ws: any, headerRow: number, footerLeft: string) {
  ws.pageSetup = {
    paperSize: 9, // A4
    orientation: "landscape",
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 0,
    horizontalCentered: true,
    margins: { left: 0.3, right: 0.3, top: 0.45, bottom: 0.5, header: 0.2, footer: 0.25 },
    printTitlesRow: `${headerRow}:${headerRow}`,
  };
  const clean = footerLeft.replace(/&/g, "and").slice(0, 80);
  ws.headerFooter = {
    oddFooter: `&L&8Biome Industria Pvt. Ltd. — ${clean}&R&8Page &P of &N`,
    evenFooter: `&L&8Biome Industria Pvt. Ltd. — ${clean}&R&8Page &P of &N`,
  };
}

export interface SummarySection {
  title: string;
  columns: XlColumn[];
  rows: Record<string, any>[];
  totals?: boolean;
}

/**
 * A summary sheet: the letterhead, then several small tables (by vendor,
 * by month…) one under the other, each with its own heading and total.
 */
export function buildSummarySheet(wb: any, name: string, meta: XlMeta, sections: SummarySection[], logoId: number | null) {
  const width = Math.max(...sections.map((s) => s.columns.length), 4);
  const ws = wb.addWorksheet(safeSheetName(name), { properties: { tabColor: { argb: XL_COLORS.brand } } });
  let r = letterhead(ws, meta, width, logoId);
  const widths: number[] = new Array(width).fill(12);

  for (const s of sections) {
    ws.mergeCells(r, 1, r, width);
    const h = ws.getCell(r, 1);
    h.value = s.title;
    h.font = { name: "Calibri", size: 11.5, bold: true, color: { argb: XL_COLORS.leaf } };
    h.border = { bottom: { style: "medium", color: { argb: XL_COLORS.leaf } } };
    ws.getRow(r).height = 20;
    r += 1;
    styleHeaderRow(ws, r, s.columns);
    const first = r + 1;
    s.rows.forEach((row, i) => {
      s.columns.forEach((c, ci) => {
        const cell = ws.getCell(first + i, ci + 1);
        const v = row[c.key];
        cell.value = c.type === "date" ? excelDate(v) : c.type && c.type !== "text" ? (Number.isFinite(Number(v)) ? Number(v) : null) : String(v ?? "");
        const fmt = numFmtFor(c.type);
        if (fmt) cell.numFmt = fmt;
        cell.font = { name: "Calibri", size: 10, color: { argb: XL_COLORS.ink } };
        cell.alignment = { vertical: "middle", horizontal: c.type && c.type !== "text" ? "right" : "left" };
        cell.border = { bottom: thin() };
        if (i % 2 === 1) cell.fill = solid(XL_COLORS.zebra);
        const len = String(v ?? "").length + 3;
        if (len > widths[ci]) widths[ci] = Math.min(40, len);
      });
    });
    s.columns.forEach((c, ci) => { widths[ci] = Math.max(widths[ci], Math.min(24, c.header.length + 2)); });
    const last = first + s.rows.length - 1;
    if (s.totals !== false && s.rows.length) {
      s.columns.forEach((c, ci) => {
        const cell = ws.getCell(last + 1, ci + 1);
        if (ci === 0) cell.value = "TOTAL";
        else if (c.total) {
          const L = colLetter(ci + 1);
          const sum = s.rows.reduce((a, x) => a + (Number(x[c.key]) || 0), 0);
          cell.value = { formula: `SUM(${L}${first}:${L}${last})`, result: round2(sum) };
          const fmt = numFmtFor(c.type);
          if (fmt) cell.numFmt = fmt;
        }
        cell.font = { name: "Calibri", size: 10.5, bold: true, color: { argb: XL_COLORS.brand } };
        cell.fill = solid(XL_COLORS.leafSoft);
        cell.border = { top: { style: "thin", color: { argb: XL_COLORS.leaf } }, bottom: { style: "double", color: { argb: XL_COLORS.leaf } } };
      });
      r = last + 3;
    } else {
      if (!s.rows.length) {
        ws.getCell(first, 1).value = "Nothing to summarise.";
        ws.getCell(first, 1).font = { italic: true, color: { argb: XL_COLORS.muted } };
        r = first + 2;
      } else r = last + 2;
    }
  }
  widths.forEach((w, i) => { ws.getColumn(i + 1).width = i === 0 ? Math.max(w, 26) : w; });
  ws.views = [{ showGridLines: false }];
  printSetup(ws, 1, `${meta.title} — summary`);
  ws.pageSetup.printTitlesRow = undefined;
  return ws;
}

/** Group rows and sum the given keys. */
export function groupSum(
  rows: Record<string, any>[],
  keyOf: (r: Record<string, any>) => string,
  sumKeys: string[],
  extra?: (first: Record<string, any>) => Record<string, any>
): Record<string, any>[] {
  const m = new Map<string, Record<string, any>>();
  for (const r of rows) {
    const k = keyOf(r) || "—";
    let g = m.get(k);
    if (!g) { g = { group: k, count: 0, ...(extra ? extra(r) : {}) }; for (const s of sumKeys) g[s] = 0; m.set(k, g); }
    g.count += 1;
    for (const s of sumKeys) { const n = Number(r[s]); if (Number.isFinite(n)) g[s] += n; }
  }
  return [...m.values()];
}

/** "2026-09" → "Sep 2026". */
export function monthLabel(iso: string): string {
  const m = String(iso || "").match(/^(\d{4})-(\d{2})/);
  if (!m) return "No date";
  return new Date(Date.UTC(Number(m[1]), Number(m[2]) - 1, 1)).toLocaleDateString("en-IN", { month: "short", year: "numeric", timeZone: "UTC" });
}

export function safeSheetName(s: string): string {
  return s.replace(/[\\/*?:\[\]]/g, "-").slice(0, 31) || "Sheet";
}

function round2(n: number) {
  return Math.round(n * 100) / 100;
}
