// Shared letterhead/footer for every PDF report generated by the
// platform, so exports look like they came from Biome Industria's own
// software rather than a generic spreadsheet dump.

let logoDataUrlPromise: Promise<string | null> | null = null;

async function getLogoDataUrl(): Promise<string | null> {
  if (!logoDataUrlPromise) {
    logoDataUrlPromise = (async () => {
      try {
        const res = await fetch("/assets/logo.png");
        if (!res.ok) return null;
        const blob = await res.blob();
        return await new Promise<string>((resolve, reject) => {
          const reader = new FileReader();
          reader.onloadend = () => resolve(reader.result as string);
          reader.onerror = () => reject(new Error("Could not read logo"));
          reader.readAsDataURL(blob);
        });
      } catch {
        return null;
      }
    })();
  }
  return logoDataUrlPromise;
}

const BRAND_GREEN: [number, number, number] = [90, 156, 78];
const INK: [number, number, number] = [22, 30, 45];
const MUTED: [number, number, number] = [110, 120, 140];
const LINE: [number, number, number] = [222, 226, 232];

/**
 * Draws the shared company letterhead (accent bar, logo, name, tagline,
 * report title/subtitle) at the top of the current page and returns the
 * y-coordinate where the report's own content should start.
 */
export async function drawLetterhead(
  doc: any,
  reportTitle: string,
  reportSubtitle: string
): Promise<number> {
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(...BRAND_GREEN);
  doc.rect(0, 0, pageWidth, 3, "F");

  const logo = await getLogoDataUrl();
  let textX = 14;
  if (logo) {
    try {
      doc.addImage(logo, "PNG", 14, 8, 14, 14);
      textX = 32;
    } catch {
      // If the logo can't be embedded for any reason, fall back to
      // text-only branding rather than failing the whole export.
    }
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12.5);
  doc.setTextColor(...INK);
  doc.text("BIOME INDUSTRIA PRIVATE LIMITED", textX, 14.5);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text("Biomass energy & industrial solutions · Enterprise Platform", textX, 19.5);

  doc.setDrawColor(...LINE);
  doc.line(14, 26, pageWidth - 14, 26);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...INK);
  doc.text(reportTitle, 14, 34);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text(reportSubtitle, 14, 40);

  return 47;
}

/** Stamps a footer (confidentiality line + page numbers) on every page
 *  of the document — call once, after all content has been drawn. */
export function drawFooter(doc: any) {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(...LINE);
    doc.line(14, pageHeight - 12, pageWidth - 14, pageHeight - 12);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...MUTED);
    doc.text(
      "Biome Industria Private Limited · Generated by the Enterprise Platform · Confidential",
      14,
      pageHeight - 7
    );
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 14, pageHeight - 7, { align: "right" });
  }
}
