"use client";
import { useCallback, useEffect, useState } from "react";
import Portal from "@/components/Portal";
import { FileSignature, Plus, Loader2, X, CheckCircle2, Circle, FileUp } from "lucide-react";
import GlassCard from "@/components/GlassCard";

/** CONTRACTS & OBLIGATIONS — expiry, renewal status, obligations that tick off, commitments; reminders come from the Work Engine. */
const RS: Record<string, string> = { not_started: "border-biome-line text-biome-muted", in_progress: "border-amber-500/40 bg-amber-500/10 text-amber-600", renewed: "border-emerald-500/40 bg-emerald-500/10 text-emerald-600", will_not_renew: "border-biome-line text-biome-muted" };
const ST: Record<string, string> = { active: "border-emerald-500/40 bg-emerald-500/10 text-emerald-600", renewal_due: "border-amber-500/40 bg-amber-500/10 text-amber-600", expired: "border-rose-500/40 bg-rose-500/10 text-rose-500" };
const input = "bmx-input w-full rounded-xl border border-biome-line bg-biome-bg px-3 py-2.5 text-[12px] text-biome-text outline-none";

export default function ContractsPage() {
  const [list, setList] = useState<any[] | null>(null); const [creating, setCreating] = useState(false); const [open, setOpen] = useState<any | null>(null); const [err, setErr] = useState<string | null>(null);
  const load = useCallback(async () => { const r = await fetch("/api/contracts", { cache: "no-store" }); const j = await r.json(); setList(j.contracts || []); }, []);
  useEffect(() => { load(); }, [load]);
  async function post(body: any) { const r = await fetch("/api/contracts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const j = await r.json().catch(() => ({})); if (!r.ok) { setErr(j.error || "Failed."); return null; } await load(); if (j.contract && open) setOpen(j.contract); return j; }
  const inr = (n: number) => `₹${Math.round(n).toLocaleString("en-IN")}`;
  return (
    <div className="space-y-5">
      <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-biome-muted">Biome AI OS</p><h1 className="biome-shout mt-1 text-[30px] leading-[1.05] text-biome-text">Contracts<span className="text-biome-leafBright">.</span></h1><p className="mt-2 text-[12px] text-biome-muted">Agreements, renewal dates, obligations and financial commitments — reminders and tasks come by themselves.</p></div><button onClick={() => setCreating(true)} className="bmx-btn flex items-center gap-2 rounded-xl bg-biome-leaf px-4 py-2.5 text-[11.5px] font-bold text-white"><Plus size={14} /> New contract</button></header>
      {err && <p className="rounded-2xl border border-rose-500/30 bg-rose-500/[.07] px-4 py-3 text-[11.5px] text-rose-500">{err}</p>}
      {!list ? <div className="flex justify-center py-20"><Loader2 size={22} className="bmx-spin text-biome-muted" /></div> : (
        <div className="space-y-1.5">{list.length === 0 && <GlassCard className="p-8 text-center"><p className="text-[12.5px] font-bold text-biome-text">No contracts yet</p></GlassCard>}
          {list.map((c) => <button key={c.id} onClick={() => setOpen(c)} className="bmx-card flex w-full flex-wrap items-center gap-2 rounded-2xl border border-biome-line bg-biome-bgSoft px-4 py-3 text-left"><FileSignature size={14} className="text-biome-leafBright" /><span className="text-[12.5px] font-semibold text-biome-text">{c.title}</span><span className="text-[10.5px] text-biome-muted">{c.party} · {c.kind}</span><span className={`rounded-full border px-2 py-0.5 text-[9px] font-bold uppercase ${ST[c.status]}`}>{c.status.replace("_", " ")}</span><span className={`rounded-full border px-2 py-0.5 text-[9px] font-bold uppercase ${RS[c.renewalStatus]}`}>renewal {c.renewalStatus.replace(/_/g, " ")}</span><span className="ml-auto text-[10.5px] text-biome-muted">{c.daysToExpiry !== null ? `expires in ${c.daysToExpiry} d` : "no expiry"} · {c.pendingObligations} pending{c.overdueObligations ? ` (${c.overdueObligations} overdue)` : ""}{c.commitments ? ` · ${inr(c.commitments)} committed` : ""}</span></button>)}
        </div>)}
      {creating && <Create onClose={() => setCreating(false)} onCreate={async (b) => { const r = await post({ action: "create", ...b }); if (r) setCreating(false); }} />}
      {open && (
        <Portal><div className="fixed inset-0 z-[210] flex items-center justify-center bg-black/45 p-4 backdrop-blur-sm" onClick={() => setOpen(null)}><div onClick={(e) => e.stopPropagation()} className="bmx-card max-h-[92vh] w-full max-w-xl overflow-auto rounded-3xl border border-biome-line bg-biome-bgSoft p-5">
          <div className="flex items-start justify-between"><div><h3 className="text-[15px] font-bold text-biome-text">{open.title}</h3><p className="text-[10.5px] text-biome-muted">{open.party} · {open.startDate} → {open.expiryDate || "—"}{open.value ? ` · ${inr(open.value)}` : ""}</p></div><button onClick={() => setOpen(null)} className="bmx-chip flex h-8 w-8 items-center justify-center rounded-lg border border-biome-line text-biome-muted"><X size={14} /></button></div>
          <p className="mt-3 text-[9.5px] font-bold uppercase tracking-[.14em] text-biome-muted">Obligations</p>
          <ul className="mt-1 space-y-1">{open.obligations.map((o: any) => <li key={o.id} className="flex items-center gap-2 text-[11.5px] text-biome-text"><button onClick={() => post({ action: "obligation", id: open.id, obligationId: o.id })}>{o.done ? <CheckCircle2 size={14} className="text-emerald-500" /> : <Circle size={14} className="text-biome-muted" />}</button><span className={o.done ? "line-through text-biome-muted" : ""}>{o.text}</span><span className="ml-auto text-[10px] text-biome-muted">{o.dueOn}{o.amount ? ` · ${inr(o.amount)}` : ""}</span></li>)}</ul>
          <AddOb onAdd={(b) => post({ action: "add-obligation", id: open.id, ...b })} />
          <p className="mt-3 text-[9.5px] font-bold uppercase tracking-[.14em] text-biome-muted">Renewal</p>
          <div className="mt-1 flex flex-wrap gap-1.5">{["not_started", "in_progress", "renewed", "will_not_renew"].map((s) => <button key={s} onClick={() => { const nx = s === "renewed" ? window.prompt("New expiry date (YYYY-MM-DD):", open.expiryDate) : null; post({ action: "renewal", id: open.id, status: s, newExpiry: nx }); }} className={`bmx-chip rounded-full border px-3 py-1.5 text-[10.5px] font-semibold ${open.renewalStatus === s ? "border-biome-leaf/50 bg-biome-leaf/12 text-biome-leafBright" : "border-biome-line text-biome-muted"}`}>{s.replace(/_/g, " ")}</button>)}</div>
          <label className="bmx-chip mt-3 inline-flex cursor-pointer items-center gap-1 rounded-xl border border-biome-line px-3 py-2 text-[11px] font-semibold text-biome-muted"><FileUp size={12} /> {open.attachment ? open.attachment.name : "Attach agreement"}<input type="file" className="hidden" onChange={async (e) => { const f = e.target.files?.[0]; if (!f) return; const b64 = await new Promise<string>((res) => { const r = new FileReader(); r.onload = () => res(String(r.result).split(",")[1]); r.readAsDataURL(f); }); await post({ action: "attach", id: open.id, fileBase64: b64, fileName: f.name }); }} /></label>
        </div></div></Portal>)}
    </div>);
}
function AddOb({ onAdd }: { onAdd: (b: any) => void }) { const [f, setF] = useState({ text: "", dueOn: "", amount: "" }); return <div className="mt-2 grid grid-cols-[1fr,120px,100px,auto] gap-1.5"><input value={f.text} onChange={(e) => setF({ ...f, text: e.target.value })} placeholder="New obligation" className={`${input} py-1.5 text-[11px]`} /><input type="date" value={f.dueOn} onChange={(e) => setF({ ...f, dueOn: e.target.value })} className={`${input} py-1.5 text-[11px]`} /><input type="number" value={f.amount} onChange={(e) => setF({ ...f, amount: e.target.value })} placeholder="₹" className={`${input} py-1.5 text-[11px]`} /><button disabled={!f.text} onClick={() => { onAdd(f); setF({ text: "", dueOn: "", amount: "" }); }} className="bmx-chip rounded-xl border border-biome-line px-3 text-[11px] font-semibold text-biome-muted disabled:opacity-50">Add</button></div>; }
function Create({ onClose, onCreate }: { onClose: () => void; onCreate: (b: any) => Promise<void> }) {
  const [f, setF] = useState({ title: "", party: "", partyType: "vendor", kind: "supply", startDate: new Date().toISOString().slice(0, 10), expiryDate: "", value: "", notes: "" });
  return <Portal><div className="fixed inset-0 z-[210] flex items-center justify-center bg-black/45 p-4 backdrop-blur-sm" onClick={onClose}><div onClick={(e) => e.stopPropagation()} className="bmx-card w-full max-w-lg rounded-3xl border border-biome-line bg-biome-bgSoft p-5"><h3 className="text-[15px] font-bold text-biome-text">New contract</h3><div className="mt-3 grid gap-2 sm:grid-cols-2"><input value={f.title} onChange={(e) => setF({ ...f, title: e.target.value })} placeholder="Title" className={`${input} sm:col-span-2`} /><input value={f.party} onChange={(e) => setF({ ...f, party: e.target.value })} placeholder="Party" className={input} /><select value={f.partyType} onChange={(e) => setF({ ...f, partyType: e.target.value })} className={input}>{["vendor", "client", "transporter", "other"].map((x) => <option key={x}>{x}</option>)}</select><select value={f.kind} onChange={(e) => setF({ ...f, kind: e.target.value })} className={input}>{["supply", "transport", "service", "lease", "other"].map((x) => <option key={x}>{x}</option>)}</select><input type="number" value={f.value} onChange={(e) => setF({ ...f, value: e.target.value })} placeholder="Value ₹" className={input} /><input type="date" value={f.startDate} onChange={(e) => setF({ ...f, startDate: e.target.value })} className={input} /><input type="date" value={f.expiryDate} onChange={(e) => setF({ ...f, expiryDate: e.target.value })} className={input} /><textarea rows={2} value={f.notes} onChange={(e) => setF({ ...f, notes: e.target.value })} placeholder="Notes" className={`${input} resize-none sm:col-span-2`} /></div><button disabled={!f.title || !f.party} onClick={() => onCreate(f)} className="bmx-btn mt-3 rounded-xl bg-biome-leaf px-5 py-2.5 text-[11.5px] font-bold text-white disabled:opacity-50">Create</button></div></div></Portal>;
}
